Rancher 186 - cypress tests pipeline #2
folio-org/pipelines-shared-library pull request #1
Opened 2022-03-03 08:43 UTC by vkapylou

2022-03-03 08:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/folio-org/pipelines-shared-library?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/folio-org/pipelines-shared-library?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/folio-org/pipelines-shared-library?pullRequest=1) it.</sub>

2022-03-07 09:45 UTC, OHaimanov requested changes

2022-03-07 09:45 UTC, OHaimanov commented on pipelines/cypress.groovy
> +                    id -u
It is unnecessary used just for permissions check

2022-03-07 09:45 UTC, OHaimanov commented on pipelines/cypress.groovy
> +                    id -g
Same to previous

2022-03-07 09:45 UTC, OHaimanov commented on pipelines/cypress.groovy
> +                    ls -la /var/lib/jenkins/workspace/scratch_environment/folio-api-tests-cypress-v2.0/target/allure-results
find and ls unnecessary used just for debug

2022-03-07 09:45 UTC, OHaimanov commented on pipelines/cypress.groovy
> +                    chown -R 497:495 *
It will be good to get this uid and gid with variables

2022-03-07 09:45 UTC, OHaimanov commented on pipelines/cypress.groovy
> +                    '''
This sh step used for debug. Could be deleted

2022-03-07 09:46 UTC, OHaimanov commented on pipelines/cypress.groovy
> +}
Newline missed

2022-03-07 09:46 UTC, OHaimanov commented on pipelines/cypress.groovy
> +#!groovy
Please do squash to have only one commit

2022-03-07 15:15 UTC, OHaimanov approved these changes

2022-03-09 13:07 UTC, merged

2022-03-09 13:15 UTC, VitalyDemchenkoEpam commented on pipelines/cypress.groovy
> +        println err
for by understanding after adding "|| true" in 68 line try/catch is not required anymore?

2022-03-09 13:15 UTC, VitalyDemchenkoEpam commented on pipelines/cypress.groovy
> +            def allure_home = tool name: '2.17.2', type: 'allure'
Hardcoded version, please move to constants

2022-03-09 13:15 UTC, VitalyDemchenkoEpam commented on pipelines/cypress.groovy
> +              commandline      : '2.17.2',
hardcoded version