Rancher 839
folio-org/pipelines-shared-library pull request #374
Opened 2023-11-22 00:23 UTC by guram-jalaghonia

Rancher 839
Draft Version
Job Works But Need Team Suggestions as well for the Good Style 

https://issues.folio.org/browse/RANCHER-839

2023-11-22 02:35 UTC, eldiiar-duishenaliev commented on pipelines/folioRancher/folioScheduledTesting/runNightlySchemaComparison/Jenkinsfile
> +@Library('pipelines-shared-library@RANCHER-839') _
Don't forget to switch to 741 branch.

2023-11-22 02:35 UTC, eldiiar-duishenaliev commented on pipelines/folioRancher/folioScheduledTesting/executeSprintBasedDataMigration/Jenkinsfile
> +          throw new Exception("Execution Of Schema Comparison Job Failed: " + new_ex)
requires .getMessage() method inclusion.

2023-11-22 02:36 UTC, eldiiar-duishenaliev commented on pipelines/folioRancher/folioScheduledTesting/runNightlySchemaComparison/Jenkinsfile
> +    string(name: 'FOLIO_BRANCH_SRC', defaultValue: 'R1-2023', description: "platform-complete source branch for the comparison"),
Should it be snapshot branch specified over here?

2023-11-22 02:38 UTC, eldiiar-duishenaliev commented on pipelines/folioRancher/folioScheduledTesting/executeSprintBasedDataMigration/Jenkinsfile
> +    string(name: 'FOLIO_BRANCH_SRC', defaultValue: 'R1-2023', description: "platform-complete source branch for the comparison"),
Specify descriptions please.

2024-02-02 10:54 UTC, renatsafiulin approved these changes

2024-02-06 09:22 UTC, eldiiar-duishenaliev commented on pipelines/folioRancher/folioTestingTools/folioSchemaCompare/Jenkinsfile
> +@Library('pipelines-shared-library@RANCHER-839') _
don't forget to switch to 741 branch

2024-02-06 09:22 UTC, eldiiar-duishenaliev commented on pipelines/folioRancher/folioScheduledTesting/executeSprintBasedDataMigration/Jenkinsfile
> +    string(name: 'FOLIO_BRANCH_SRC', defaultValue: 'R1-2023', description: "platform-complete source branch for the comparison"),
switch to default value with R2-2023(Poppy)

2024-02-06 09:23 UTC, eldiiar-duishenaliev requested changes
Please review my comments.

2024-02-06 11:25 UTC, DmytrMoroz commented on pipelines/folioRancher/folioTestingTools/folioSchemaCompare/Jenkinsfile
> +@Library('pipelines-shared-library@RANCHER-839') _
done

2024-02-06 11:52 UTC, merged