RANCHER-1229 add dev cluster condition
folio-org/pipelines-shared-library pull request #474
Opened 2024-04-23 08:46 UTC by aatoyan

2024-04-23 12:07 UTC, yaroslavishchenko approved these changes

2024-04-23 13:17 UTC, OHaimanov requested changes

2024-04-23 18:23 UTC, aatoyan commented on vars/folioHelm.groovy
> +  if (params.cluster == 'folio-dev') {
something like this?

2024-04-24 07:28 UTC, OHaimanov approved these changes

2024-04-24 07:31 UTC, merged