Rancher 311v1 ADD REINDEX ELASTICSEARCH
folio-org/pipelines-shared-library pull request #52
Opened 2022-06-17 07:51 UTC by MaryiaLazavik

2022-06-17 08:26 UTC, OHaimanov requested changes

2022-06-17 08:26 UTC, OHaimanov commented on pipelines/rancher/project.groovy
> +@Library('pipelines-shared-library@RANCHER-311V1') _
Before merge remove this version in lib

2022-06-17 08:26 UTC, OHaimanov commented on vars/jobsParameters.groovy
> +    return _paramBoolean('reIndexElasticsearch', true, 'True if need to reindex modules, default value: true')
please refactor param name from camelCase to snake_case

2022-06-17 08:26 UTC, OHaimanov commented on vars/jobsParameters.groovy
> +    return _paramBoolean('recreateIndexElasticsearch', false, 'True if need to recreate index modules , default value: false')
please refactor param name from camelCase to snake_case

2022-06-17 08:26 UTC, OHaimanov commented on src/org/folio/rest/Okapi.groovy
> +        }
This should be a separate method

2022-06-17 08:26 UTC, OHaimanov commented on src/org/folio/rest/TenantService.groovy
> +                return (test)
what is the purpose of this test return?

2022-06-17 08:51 UTC, TarasSpashchenko requested changes
@MaryiaLazavik please fix the comments provided by @OHaimanov

2022-06-21 07:41 UTC, VitalyDemchenkoEpam commented on src/org/folio/rest/Okapi.groovy
> +        steps.timeout(15) {
I think 15 seconds is too low. I think 10-12 hours much better value.

2022-06-21 07:41 UTC, VitalyDemchenkoEpam commented on src/org/folio/rest/Okapi.groovy
> +                        logger.info("reindex successufully completed")
unreachable code, as you have "return" on a previous line. I think "return" should be removed

2022-06-21 07:41 UTC, VitalyDemchenkoEpam commented on src/org/folio/rest/Okapi.groovy
> +                    } else {
looks like this "else" must be for "res.status == HttpURLConnection.HTTP_OK" if.

2022-06-21 11:24 UTC, VitalyDemchenkoEpam approved these changes

2022-06-21 11:51 UTC, OHaimanov requested changes

2022-06-21 11:51 UTC, OHaimanov commented on src/org/folio/rest/Okapi.groovy
> +    def reindex_elastic_search(tenant, admin_user, recreate_index_elastic_search) {
Please rename method to camelCase

2022-06-22 20:02 UTC, Volodymyr-Kartsev approved these changes

2022-06-23 12:46 UTC, OHaimanov approved these changes

2022-06-23 13:55 UTC, merged