RANCHER-396
folio-org/pipelines-shared-library pull request #80
Opened 2022-08-31 07:53 UTC by Volodymyr-Kartsev

2022-08-31 09:44 UTC, vkapylou approved these changes

2022-09-05 08:40 UTC, OHaimanov approved these changes

2022-09-05 08:41 UTC, OHaimanov requested changes
Please adjust it to new approach

2022-09-07 11:22 UTC, Volodymyr-Kartsev commented
The ticket was reworked to be compatible with the RANCHER-261 changes in the scope of RANCHER-433.

2022-09-07 11:22 UTC, closed without merging